version: '2.4'

services:

  blescanner:
    image: registry.messner.click/gunny26/docker-blescanner:latest
    container_name: blescanner
    restart: unless-stopped
    mem_limit: 128m
    cpu_count: 2
    privileged: true
    volumes:
      - /run/dbus:/run/dbus:ro
    ports:
      - 8000:8000
    environment:
      TZ: Europe/Vienna
      APP_LOG_LEVEL: INFO  # to use in logging
      APP_INTERVAL: 20  # seconds
